import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,stat} from 'node:fs/promises';
import {join,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import worker from '../dist/_worker.js';
const root=join(dirname(fileURLToPath(import.meta.url)),'../dist');
const assets={async fetch(req){let path=join(root,new URL(req.url).pathname);try{if((await stat(path)).isDirectory())path=join(path,'index.html');return new Response(req.method==='HEAD'?null:await readFile(path));}catch{return new Response('',{status:404});}}};
function environment(overrides={}){return{ASSETS:assets,CONTACT_ENABLED:'true',TURNSTILE_SITE_KEY:'0x4AAAAAAAvalid-looking-test-site-key',CONTACT_WORKER:{fetch:async()=>new Response(JSON.stringify({ok:true,reference:'test'}),{headers:{'Content-Type':'application/json'}})},...overrides};}
async function get(path='/',host='etamade.com',options={}){return worker.fetch(new Request(`https://${host}${path}`,options),environment());}
for(const [host,lang]of [['etamade.com','en'],['etamade.ro','ro']]){
  test(`${host} delivers pre-rendered ${lang} with canonical and hreflang`,async()=>{const r=await get('/',host);assert.equal(r.status,200);assert.equal(r.headers.get('content-language'),lang);const text=await r.text();assert.ok(text.includes(`<html lang="${lang}">`));assert.ok(text.includes(`rel="canonical" href="https://${host}/"`));assert.ok(text.includes('hreflang="en"'));assert.ok(text.includes('hreflang="ro"'));assert.ok(text.includes('id="contact-form"'));assert.ok(text.includes('ETAMADE S.R.L.'));assert.ok(!text.includes('under construction'));assert.ok(r.headers.get('content-security-policy').includes('https://challenges.cloudflare.com'));});
  test(`${host} ignores query-based production language override`,async()=>{const r=await get(`/?lang=${lang==='en'?'ro':'en'}`,host);assert.equal(r.headers.get('content-language'),lang);});
  test(`www.${host} redirects preserving path and query`,async()=>{const r=await get('/?x=1',`www.${host}`);assert.equal(r.status,308);assert.equal(r.headers.get('location'),`https://${host}/?x=1`);});
  for(const [path,type]of [['/llms.txt','text/plain'],['/llms-full.txt','text/plain'],['/index.md','text/markdown'],['/services.md','text/markdown'],['/contact.md','text/markdown'],['/company.json','application/json'],['/robots.txt','text/plain'],['/sitemap.xml','application/xml']]){
    test(`${host}${path} serves correct machine-readable content`,async()=>{const r=await get(path,host);assert.equal(r.status,200);assert.ok(r.headers.get('content-type').includes(type));assert.equal(r.headers.get('content-language'),lang);const text=await r.text();assert.ok(text.length>50);assert.ok(!text.startsWith('<!doctype html>'));if(path==='/company.json')assert.equal(JSON.parse(text).language,lang);if(path==='/llms.txt')assert.ok(text.includes(`https://${host}/index.md`));});
  }
}
test('local preview explicitly selects Romanian',async()=>{const r=await worker.fetch(new Request('http://localhost:8788/?lang=ro'),environment());assert.equal(r.status,200);assert.equal(r.headers.get('content-language'),'ro');assert.equal(r.headers.get('x-robots-tag'),'noindex, nofollow');});
test('pages.dev preview is noindex',async()=>{const r=await get('/','abc.etamade-website.pages.dev');assert.equal(r.status,200);assert.equal(r.headers.get('x-robots-tag'),'noindex, nofollow');});
test('pages.dev preview robots disallows indexing',async()=>{const r=await get('/robots.txt','etamade-website.pages.dev');assert.match(await r.text(),/Disallow: \//);});
test('unknown host is rejected, not mirrored',async()=>{assert.equal((await get('/','attacker.example')).status,421);});
test('preview form is disabled even with production bindings',async()=>{const r=await get('/api/config','etamade-website.pages.dev');const value=await r.json();assert.equal(value.enabled,false);assert.equal(value.siteKey,null);});
test('enabled production config exposes only public fields',async()=>{const r=await get('/api/config');const value=await r.json();assert.equal(value.enabled,true);assert.deepEqual(Object.keys(value).sort(),['enabled','siteKey']);assert.equal(r.headers.get('cache-control'),'no-store');});
test('a missing service binding disables form',async()=>{const r=await worker.fetch(new Request('https://etamade.com/api/config'),environment({CONTACT_WORKER:undefined}));assert.equal((await r.json()).enabled,false);});
test('known dummy site key cannot enable production form',async()=>{const r=await worker.fetch(new Request('https://etamade.com/api/config'),environment({TURNSTILE_SITE_KEY:'1x00000000000000000000AA'}));assert.equal((await r.json()).enabled,false);});
test('origin check runs before private Worker',async()=>{let called=false;const r=await worker.fetch(new Request('https://etamade.com/api/contact',{method:'POST',headers:{Origin:'https://attacker.example'},body:'{}'}),environment({CONTACT_WORKER:{fetch:async()=>{called=true;return new Response();}}}));assert.equal(r.status,403);assert.equal(called,false);});
test('gateway overwrites visitor-supplied internal IP header',async()=>{let ip;const r=await worker.fetch(new Request('https://etamade.com/api/contact',{method:'POST',headers:{Origin:'https://etamade.com','CF-Connecting-IP':'192.0.2.55','X-ETAMADE-Client-IP':'attacker'},body:'{}'}),environment({CONTACT_WORKER:{fetch:async req=>{ip=req.headers.get('x-etamade-client-ip');return new Response('{"ok":true}');}}}));assert.equal(r.status,200);assert.equal(ip,'192.0.2.55');});
test('GET contact never invokes service',async()=>{const r=await get('/api/contact');assert.equal(r.status,405);});
test('OPTIONS cannot open cross-origin access',async()=>{const r=await get('/api/contact','etamade.com',{method:'OPTIONS'});assert.equal(r.status,405);assert.equal(r.headers.has('access-control-allow-origin'),false);});
test('Markdown content negotiation returns actual Markdown',async()=>{const r=await get('/','etamade.com',{headers:{Accept:'text/markdown'}});assert.equal(r.headers.get('content-type'),'text/markdown; charset=utf-8');assert.equal(r.headers.get('vary'),'Accept');assert.ok((await r.text()).startsWith('# ETAMADE'));});
test('normal browser accepts HTML even if Markdown also accepted',async()=>{const r=await get('/','etamade.com',{headers:{Accept:'text/html,text/markdown'}});assert.ok(r.headers.get('content-type').includes('text/html'));});
test('HEAD returns correct headers and no body',async()=>{const r=await get('/','etamade.ro',{method:'HEAD'});assert.equal(r.status,200);assert.equal(r.headers.get('content-language'),'ro');assert.equal(await r.text(),'');});
test('missing page is a genuine translated 404',async()=>{const r=await get('/missing','etamade.ro');assert.equal(r.status,404);assert.ok((await r.text()).includes('Nu am g'));});
test('internal localized asset paths cannot be requested directly',async()=>{const r=await get('/_site/en/','etamade.ro');assert.equal(r.status,404);});
test('privacy and legal aliases redirect to localized slugs',async()=>{const r=await get('/privacy/','etamade.ro');assert.equal(r.status,308);assert.equal(r.headers.get('location'),'https://etamade.ro/confidentialitate/');const r2=await get('/informatii-legale/','etamade.com');assert.equal(r2.headers.get('location'),'https://etamade.com/legal/');});
test('no-trailing-slash legal URL canonicalizes',async()=>{assert.equal((await get('/privacy')).headers.get('location'),'https://etamade.com/privacy/');});
test('all inline structured data has a valid CSP hash and valid JSON',async()=>{for(const host of ['etamade.com','etamade.ro'])for(const path of ['/','/privacy/','/confidentialitate/','/legal/','/informatii-legale/']){const r=await get(path,host);if(r.status!==200)continue;const csp=r.headers.get('content-security-policy'),html=await r.text();for(const m of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)){assert.ok(JSON.parse(m[1])['@graph'].length>=3);assert.ok(csp.includes(createHash('sha256').update(m[1]).digest('base64')));}}});
test('built documents do not include source placeholders or secrets',async()=>{const r=await get('/');const html=await r.text();assert.ok(!html.includes('__BUILD_CONFIG__'));assert.ok(!html.includes('TURNSTILE_SECRET_KEY'));assert.ok(!html.includes('RATE_LIMIT_SALT'));assert.ok(!html.includes('IBAN'));});

test('config endpoint rejects POST with correct Allow header',async()=>{const r=await get('/api/config','etamade.com',{method:'POST'});assert.equal(r.status,405);assert.equal(r.headers.get('allow'),'GET, HEAD');});
